INSERT INTO ref_Gewicht (Einheit)
VALUES ('t'),
       ('kg'),
       ('g');

INSERT INTO ref_Groesse (Einheit)
VALUES ('m'),
       ('cm'),
       ('mm');

INSERT INTO ref_Lagereinheit_Futter (Einheit)
VALUES ('Ballen'),
       ('Rollen'),
       ('Stück'),
       ('Sack'),
       ('kg'),
       ('g');

INSERT INTO ref_Groesseneinheit_Gehege (Einheit)
VALUES ('m2'),
       ('m3');

INSERT INTO ref_Waehrung (Einheit)
VALUES ('Euro'),
       ('US-Dollar'),
       ('Australischer Dollar'),
       ('Pfund Sterling');

INSERT INTO ref_Anrede (Anrede)
VALUES ('Herr'),
       ('Frau');

INSERT INTO ref_Titel (Titel)
VALUES ('Dr.'),
       ('Dr. med.'),
       ('Prof.'),
       ('Prof. Dr.');

INSERT INTO ref_Vertretungsgruende (Vertretungsgrund)
VALUES ('Krankheit'),
       ('Urlaub'),
       ('Schwangerschaft'),
       ('Fortbildung'),
       ('Sonstige');

INSERT INTO ref_MwSt (MwSt_Satz)
VALUES (19),
       (7);

INSERT INTO ref_hSex (hSex)
VALUES ('männlich'),
       ('weiblich');

INSERT INTO ref_aSex (aSex)
VALUES ('männlich'),
       ('weiblich'),
       ('zwitter');

INSERT INTO ref_Nation (Nation) VALUES 
("Afghanistan"),
("Ägypten"),
("Åland"),
("Albanien"),
("Algerien"),
("Amerikanische Jungferninseln"),
("Amerikanisch-Samoa"),
("Andorra"),
("Angola"),
("Anguilla"),
("Antarktika"),
("Antigua und Barbuda"),
("Äquatorialguinea"),
("Argentinien"),
("Armenien"),
("Aruba"),
("Aserbaidschan"),
("Äthiopien"),
("Australien"),
("Bahamas"),
("Bahrain"),
("Bangladesch"),
("Barbados"),
("Bassas da India"),
("Belarus"),
("Belgien"),
("Belize"),
("Benin"),
("Bermuda"),
("Bhutan"),
("Bolivien"),
("Bosnien und Herzegowina"),
("Botsuana"),
("Bouvetinsel"),
("Brasilien"),
("Britische Jungferninseln"),
("Britisches Territorium im Indischen Ozean"),
("Brunei Darussalam"),
("Bulgarien"),
("Burkina Faso"),
("Burundi"),
("Cabo Verde"),
("Chile"),
("China"),
("Clipperton"),
("Cookinseln"),
("Costa Rica"),
("Côte d’Ivoire"),
("Dänemark"),
("Deutschland"),
("Dominica"),
("Dominikanische Republik"),
("Dschibuti"),
("Ecuador"),
("El Salvador"),
("Eritrea"),
("Estland"),
("Eswatini"),
("Europa"),
("Falklandinseln"),
("Färöer"),
("Fidschi"),
("Finnland"),
("Frankreich"),
("Frankreich (metropolitanes)"),
("Französische Süd- und Antarktisgebiete"),
("Französisch-Guayana"),
("Französisch-Polynesien"),
("Gabun"),
("Gambia"),
("Gazastreifen"),
("Georgien"),
("Ghana"),
("Gibraltar"),
("Glorieuses"),
("Grenada"),
("Griechenland"),
("Grönland"),
("Großbritannien"),
("Guadeloupe"),
("Guam"),
("Guatemala"),
("Guernsey"),
("Guinea"),
("Guinea-Bissau"),
("Guyana"),
("Haiti"),
("Heard und McDonaldinseln"),
("Honduras"),
("Hongkong"),
("Indien"),
("Indonesien"),
("Insel Man"),
("Irak"),
("Iran"),
("Irland"),
("Island"),
("Israel"),
("Italien"),
("Jamaika"),
("Japan"),
("Jemen"),
("Jersey"),
("Jordanien"),
("Juan de Nova"),
("Kaimaninseln"),
("Kambodscha"),
("Kamerun"),
("Kanada"),
("Kasachstan"),
("Katar"),
("Kenia"),
("Kirgisistan"),
("Kiribati"),
("Kleinere Amerikanische Überseeinseln"),
("Kokosinseln (Keelinginseln)"),
("Kolumbien"),
("Komoren"),
("Kongo"),
("Kongo, Demokratische Republik"),
("Korea, Demokratische Volksrepublik"),
("Korea, Republik"),
("Kroatien"),
("Kuba"),
("Kuwait"),
("Laos"),
("Lesotho"),
("Lettland"),
("Libanon"),
("Liberia"),
("Libyen"),
("Liechtenstein"),
("Litauen"),
("Luxemburg"),
("Macau"),
("Madagaskar"),
("Malawi"),
("Malaysia"),
("Malediven"),
("Mali"),
("Malta"),
("Marokko"),
("Marshallinseln"),
("Martinique"),
("Mauretanien"),
("Mauritius"),
("Mayotte"),
("Mexiko"),
("Mikronesien"),
("Moldau"),
("Monaco"),
("Mongolei"),
("Montenegro"),
("Montserrat"),
("Mosambik"),
("Myanmar"),
("Namibia"),
("Nauru"),
("Nepal"),
("Neukaledonien"),
("Neuseeland"),
("Nicaragua"),
("Niederlande"),
("Niederländische Antillen"),
("Niger"),
("Nigeria"),
("Niue"),
("Nördliche Marianen"),
("Nordmazedonien"),
("Norfolkinsel"),
("Norwegen"),
("Oman"),
("Österreich"),
("Pakistan"),
("Palau"),
("Panama"),
("Papua-Neuguinea"),
("Paraguay"),
("Peru"),
("Philippinen"),
("Pitcairninseln"),
("Polen"),
("Portugal"),
("Puerto Rico"),
("Réunion"),
("Ruanda"),
("Rumänien"),
("Russische Föderation"),
("Saint-Martin"),
("Salomonen"),
("Sambia"),
("Samoa"),
("San Marino"),
("São Tomé und Príncipe"),
("Saudi-Arabien"),
("Schweden"),
("Schweiz"),
("Senegal"),
("Serbien"),
("Serbien und Montenegro"),
("Seychellen"),
("Sierra Leone"),
("Simbabwe"),
("Singapur"),
("Slowakei"),
("Slowenien"),
("Somalia"),
("Spanien"),
("Spitzbergen"),
("Sri Lanka"),
("St. Barthélemy"),
("St. Helena, Ascension und Tristan da Cunha"),
("St. Kitts und Nevis"),
("St. Lucia"),
("St. Pierre und Miquelon"),
("St. Vincent und die Grenadinen"),
("Südafrika"),
("Sudan"),
("Südgeorgien und die Südlichen Sandwichinseln"),
("Südsudan"),
("Suriname"),
("Syrien"),
("Tadschikistan"),
("Taiwan"),
("Tansania"),
("Thailand"),
("Timor-Leste"),
("Togo"),
("Tokelau"),
("Tonga"),
("Trinidad und Tobago"),
("Tromelin"),
("Tschad"),
("Tschechische Republik"),
("Tunesien"),
("Türkei"),
("Turkmenistan"),
("Turks- und Caicosinseln"),
("Tuvalu"),
("Uganda"),
("Ukraine"),
("Ungarn"),
("Uruguay"),
("Usbekistan"),
("Vanuatu"),
("Vatikanstadt"),
("Venezuela"),
("Vereinigte Arabische Emirate"),
("Vereinigte Staaten"),
("Vietnam"),
("Wallis und Futuna"),
("Weihnachtsinsel"),
("Westjordanland"),
("Westsahara"),
("Zentralafrikanische Republik"),
("Zypern");




